server:
  port: 80
spring:
  datasource:
    username: postgres
    password: S@njarbek372
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:8080/school-books
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
  main:
    lazy-initialization: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 353231268560-92lg26ouaqsa4g1emlhprlqajn33n3mr.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
jwt:
  secretKey: SupperKey
  expireTime: 864000000

